networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.22.2
    container_name: gitea
    environment:
      - USER_UID={USER_UID}
      - USER_GID={USER_GID}
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

x-nexterm:
  name: Gitea
  version: 1.22.2
  description: Private, Fast, Reliable DevOps Platform
  icon: https://raw.githubusercontent.com/gnmyt/Nexterm-AppStore/main/logos/Gitea.png
  preInstallCommand: sed -i 's/{USER_UID}/$(id -u)/g' {appPath}/docker-compose.yml && sed -i 's/{USER_GID}/$(id -g)/g' {appPath}/docker-compose.yml
  category: Development
  port: 3000